name: fruits_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  cloud_firestore: ^5.6.8
  cupertino_icons: ^1.0.8
  dartz: ^0.10.1
  dots_indicator: ^4.0.1
  firebase_auth: ^5.5.4
  firebase_core: ^3.13.1
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  # flutter_facebook_auth: ^7.1.2
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.1.0
  get_it: ^8.0.3
  google_fonts: ^6.2.1
  google_sign_in: ^6.3.0
  modal_progress_hud_nsn: ^0.5.1
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_launcher_icons: ^0.14.3
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/app_icon.png"
  min_sdk_android: 21

flutter_assets:
  assets_path: assets/images/
  output_path: lib/core/utils/
  filename: app_images.dart
  field_prefix: resource

flutter_intl:
  enabled: true
